name: 'experimentation_framework'
version: '1.0'
config-version: 2

profile: 'experimentation_framework'

model-paths: ['models']
seed-paths: ['seeds']
log-path: 'logs'
target-path: 'target'

models:
  +materialized: view

seeds:
  +schema: analytics
  +quote_columns: false