version: 2

models:
  - name: assignments
    description: "Raw experiment assignments with user_id, experiment_id, variant, assigned_at"
    columns:
      - name: user_id
        tests: [not_null]
      - name: experiment_id
        tests: [not_null]
      - name: variant
        tests: [not_null]

  - name: outcomes
    description: "Raw outcomes with user_id, metrics captured at appropriate windows"
    columns:
      - name: user_id
        tests: [not_null]

  - name: experiment_facts
    description: "Joined facts table per experiment with metrics and windows"
    tests:
      - unique:
          column_name: "user_id || '-' || experiment_id"


